### ISSUE TITLE
IsoDep sendCommand error: PlatformException(io_exception, Tag was lost., null, null)

### ISSUE THREAD

**Issue by sltc-dev** [okadan/flutter-nfc-manager#201]
Using IsoDep sendCommand to retrieve face image data on Android results in the following error (other information is retrieved successfully); the same command works correctly on iOS with ISO7816 

```dart
I/flutter ( 2136): response : 90 00
I/flutter ( 2136): response : c0 04 30 30 30 31 90 00
I/flutter ( 2136): response : c1 01 31 90 00
I/flutter ( 2136): response : aa be bb c1 71 c3 cb 95 90 00
I/flutter ( 2136): response : 7d 31 c2 00 d1 f2 be b5 2c f5 8f c3 f0 b7 bf b1 13 9b 56 8c db 8f 37 6c 45 76 1b 0f 3f 70 55 a2 3b ee f3 04 c0 56 b2 a9 90 00
I/flutter ( 2136): response : 90 00
I/flutter ( 2136): response : 90 00
I/flutter ( 2136): PlatformException(io_exception, Tag was lost., null, null)
E/flutter ( 2136): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(io_exception, Tag was lost., null, null)
E/flutter ( 2136): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 2136): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 2136): <asynchronous suspension>
E/flutter ( 2136): #2      IsoDep.transceive.<anonymous closure> (package:nfc_manager/src/platform_tags/iso_dep.dart:60:13)
E/flutter ( 2136): <asynchronous suspension>
E/flutter ( 2136): #3      IsoDepNfcTagService.sendCommand (package:cagra_app/frameworks/iso_dep_nfc_tag_service.dart:14:32)
E/flutter ( 2136): <asynchronous suspension>
E/flutter ( 2136): #4      ResidenceCardService._sendCommand (package:cagra_app/residence_card/residence_card_service.dart:193:35)
```

**Comment by Dohmanlechx** [comment]
@sitc-dev why did you close this issue? I'm seeing same problem right now.
